# Generated by Django 5.2.5 on 2025-10-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0010_uploadfile_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="women",
            name="photo",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="photos/%Y%M%D",
                verbose_name="фото",
            ),
        ),
        migrations.AlterField(
            model_name="uploadfile",
            name="file",
            field=models.FileField(upload_to="uploads_model"),
        ),
    ]
