# Generated by Django 5.2.5 on 2025-10-09 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0011_women_photo_alter_uploadfile_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tagpost",
            old_name="tag",
            new_name="name",
        ),
    ]
