# Generated by Django 5.2.5 on 2025-10-11 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0012_rename_tag_tagpost_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="women",
            name="cat",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="posts",
                to="women.category",
                verbose_name="Категории",
            ),
        ),
    ]
