# Generated by Django 5.2.5 on 2025-10-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0015_alter_women_cat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadfile",
            name="file",
            field=models.FileField(upload_to="uploads_model/%Y%M%D"),
        ),
    ]
